[package]
name = "xcrond"
version = "0.1.1"
authors = ["Siddharth Yadav <siddharth_yadav@outlook.com>"]
edition = "2018"

[dependencies]
nix = "0.12.0"
log = "0.4"
env_logger = "0.6.0"
syslog = "^4.0"
cron = { git = "https://github.com/Xk0nSid/cron" }
chrono = "0.4.6"
ctrlc = "3.1.2"
